services:
  pdf-host:
    build:
      context: ./pdf-host
      dockerfile: Dockerfile
    image: needs/pdf-host:latest
    environment:
      SPRING_APPLICATION_JSON: |
        { "server": { "port": 10081 } }
    ports:
      - "10081:10081"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:10081/jsprice/sample"]
      interval: 10s
      timeout: 5s
      retries: 10

  jsprice-converter:
    build:
      context: ./jsprice-converter
      dockerfile: Dockerfile
    image: needs/jsprice-converter:latest
    ports:
      - "10080:10080"   # ← ホスト10080で公開
    volumes:
      - ./data:/data
    environment:
      SPRING_APPLICATION_JSON: |
        {
          "server": { "port": 10080 },
          "app": {
            "sourceUrl": "http://pdf-host:10081/jsprice/sample",
            "output": { "dir": "/data/output", "filename": "jsprice_20250630.csv" }
          }
        }
      APP_DEBUG_EVERYMINUTE: "true"
    depends_on:
      pdf-host:
        condition: service_healthy

  csv-postprocessor:
    build:
      context: ./csv-postprocessor
      dockerfile: Dockerfile
    image: needs/csv-postprocessor:latest
    environment:
      SPRING_APPLICATION_JSON: |
        {
          "server": { "port": 10082 },
          "app": {
            "inDir": "/data/output",
            "outDir": "/data/txt",
            "replaceCommaWithTab": true
          },
          "camel": { "springboot": { "main-run-controller": true } }
        }
    volumes:
      - ./data:/data
    ports:
      - "10082:10082"   # ← ホスト10082で公開
    depends_on:
      jsprice-converter:
        condition: service_started
    restart: unless-stopped
